name: dictlib
description: A dictionary iterator library for Dart.
version: 1.0.1
license: MIT
repository: https://github.com/yhojann-cl/dart-dictlib

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
